"""
Vercel serverless function entry point for PoE2 Arbitrage Calculator

This uses the simplified static data API that reads from JSON files
generated by GitHub Actions every 5 minutes.
"""

# Import the simplified FastAPI app that reads from static JSON files
from simple_app import app

# This is the entry point for Vercel
handler = app
