"""
Vercel serverless function entry point for PoE2 Arbitrage Calculator

This uses the simplified static data API that reads from JSON files
generated by GitHub Actions every 5 minutes.
"""

# Import the simplified FastAPI app that reads from static JSON files
try:
    from .simple_app import app
except ImportError:
    # Fallback for different import contexts
    import sys
    import os
    sys.path.insert(0, os.path.dirname(__file__))
    from simple_app import app

# This is the entry point for Vercel
handler = app
